spring:
  application:
    name: MOVIE-INFO-SERVICE


server:
  port: 8086

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery-service-svc:8761/eureka}
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"